[package]
name = "shroud"
version = "0.1.0"
edition = "2021"
description = "universal library for graphics hooking directx9, directx10, directx11, directx12, openGl, vulcan"
license = "MIT"
readme = "README.md"
repository = "https://github.com/0xFounders/shroud"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winapi = { version = "0.3.9", default-features = false, optional = true }

log = "0.4.17"
thiserror = "1.0.37"

strum = "0.24.1"
strum_macros = "0.24.3"

[features]
default = []

opengl = ["winapi/libloaderapi"]
vulkan = ["winapi/libloaderapi"]
directx9 = ["winapi/d3d9","winapi/winuser","winapi/libloaderapi"]
directx10 = []
directx11 = ["winapi/d3d11","winapi/winuser","winapi/libloaderapi"]
directx12 = ["winapi/d3d12","winapi/dxgi","winapi/winuser","winapi/libloaderapi"]