[package]
name = "shroud"
version = "0.1.0"
edition = "2021"
description = "universal library for graphics hooking directx9, directx10, directx11, directx12, openGl, vulcan"
license = "MIT"
readme = "README.md"
repository = "https://github.com/0xFounders/shroud"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi", "d3d11", "d3d12", "d3d9"] }
libloading = "0.7.3"

log = "0.4.17"
thiserror = "1.0.37"

strum = "0.24.1"
strum_macros = "0.24.3"